version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql_user_auth
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_authentication
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
